#!/usr/bin/env bash
# Transfers a file from Holberton's client to another.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.
# ./0-transfer_file sample.html 3.83.227.12  ubuntu  ~/.ssh/id_rsa
# scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r  0x0C-web_server  ubuntu@3.83.227.12:~
# sed -i -e 's/\r$//' 0-transfer_file

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

