#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown -R ${USER}:${USER} /var/www/html
chmod -R 755 /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start

