#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y --no-install-recommends software-properties-common
# apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
# add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
#apt-get install -y haproxy=1.8.\*
apt-get install -y haproxy=2.6.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 119023-web-01 3.83.227.12:80 check
   server 119023-web-02 54.82.135.251:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
